### PR TITLE
Fix downloading layout

### LINKED ISSUE #964: layout glitch when downloading
image

### PR DESCRIPTION
**Pull request by yschimke**
#### WHAT

Fix downloading layout

#### WHY

fixes #964

#### Checklist :clipboard:
- [x] Add explicit visibility modifier and explicit return types for public declarations
- [x] Run spotless check
- [x] Run tests
- [x] Update metalava's signature text files

### CODE REVIEW

File: media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt [hunk 1]
```diff
@@ -303,7 +307,6 @@ private fun ButtonsContent(
                         onCancelDownloadButtonClick = onCancelDownloadButtonClick,
                         onDownloadCompletedButtonClick = onDownloadCompletedButtonClick,
                         modifier = Modifier
-                            .padding(start = 6.dp)
```
Comment (yschimke) [inline media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt:306]: This appeared to be extra

Comment (luizgrp) [reply media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt:306]: does it look ok on different screen sizes after the changes? judging by the snapshot images updated, we might be missing snapshot tests on small round devices

**Review by luizgrp — APPROVED** [review]

File: media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt (hunk 1 above)
Comment (luizgrp) [reply media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt:306]: it can be checked in the [preview](https://github.com/google/horologist/blob/fddd18d3dd3df4dcb70e41a4d802a9f7653576be/media-ui/src/debug/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreenPreview.kt)

Comment (yschimke) [reply media-ui/src/main/java/com/google/android/horologist/media/ui/screens/entity/PlaylistDownloadScreen.kt:306]: I used the preview.
